# Generated by Django 5.1.2 on 2024-10-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_respostas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('data_contratacao', models.DateField()),
            ],
        ),
    ]
